<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>latestmajor</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.16.0-preview.1" />
        <PackageReference Include="OscCore" Version="1.0.5" />
        <PackageReference Include="Rug.Osc" Version="1.2.5" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\FastOSC\FastOSC.csproj"/>
    </ItemGroup>

</Project>